### ISSUE TITLE
provide a jar?

### ISSUE THREAD

**Issue by villesau** [dsilva/webstorm-plugin-flow-typecheck#1]
Could you provide a built version of this project?

**Comment by mekdev** [comment]
+1 a built version would be great. Right now I am not sure how I would install this since I have 0 exp with webstorm plugin development

**Comment by dsilva** [comment]
Can you please try this jar?

https://github.com/dsilva/webstorm-plugin-flow-typecheck/releases/tag/1.0

**Comment by dsilva** [comment]
Actually, please wait -- there's a blocker bug in there (and in the subsequent 1.1) where it can't resolve imports of the form "../some/file"

**Comment by cem2ran** [comment]
I believe you can solve this by simply omitting `check-contents` on line [189](https://github.com/dsilva/webstorm-plugin-flow-typecheck/blob/6210be8f7d795133eee0d72984a6ce845bea14fa/src/com/github/dsilva/flowtc/FlowTypeCheckInspection.java#L189) as this will then contain the context required to resolve imports. 
I would have tested this myself, but I haven't been successful in setting up the plugin development environment. :(

**Comment by dsilva** [comment]
If we omit check-contents, then Flow won't read stdin.

The larger problem is that when the IDE kicks off a local inspection or an external annotator, it may not have written the current state of the editor to disk yet.  So you make a change, for example you change "const n: number = 5" to "const n: number = 'foo'" and the IDE calls the plugin.  The plugin can read the editor contents and see the latest changes, but on disk it still says "const n: number = 5".

At that point, if we just run flow, it won't report any errors.  If we pass the contents through stdin, we run into https://github.com/facebook/flow/issues/1910

Maybe this plugin shouldn't be either a local inspection or external annotator, but rather some other extension point that only kicks off after writes to the filesystem.

**Comment by cem2ran** [comment]
Right. Was not aware of the fact that inspections could happen before write to disk. Thanks for clarifying. I did a bit more digging into [how the nuclide plugin for atom does the checking](https://github.com/facebook/nuclide/blob/064ed48fa95d2ad715891d802a52e593db5418bb/pkg/nuclide-flow-rpc/lib/FlowRoot.js#L132), as it seems to be able to do this without the observed error. It looks like the command you are running is simply missing a file path. i.e.

`flow check-contents file.js < file.js` instead of `flow check-contents < file.js`.

`flow check-contents --help` seems to indicate that the above is equivalent, but it clearly isn't.

**Comment by dsilva** [comment]
Thank you :) That does work.  Try it out: https://github.com/dsilva/webstorm-plugin-flow-typecheck/releases/tag/1.2
